### ISSUE TITLE
Firepad Monaco editor not syncing correctly on block comments

### ISSUE THREAD

**Issue by derektlo** [FirebaseExtended/firepad#313] opened 2018-10-24 17:48 UTC
### Version info

**Firebase:** 3.3.0

**Firepad:** 1.5.0

**Monaco:** 0.14.3

### Test case

Write any code and then do `cmd+/` to comment the code all at once. If you have multiple pads open, they will go out of sync.

### Steps to reproduce

Path 1 (comments)
1. Write any code
2. Open up at least 2 windows on the same pad
2. Press `cmd+/`

Path 2 (multiple cursors in general)
1. Write a few lines of code
2. Select multiple edit points w/ the multiple cursor feature (cmd+click)
3. Start typing and you will notice the pads go out of sync

### Expected behavior

The pads should stay in sync.

### Actual behavior

The pads go out of sync.

**Comment by garytryan** [comment] 2018-10-24 17:51
I wonder if it could be related to: https://github.com/FirebaseExtended/firepad/pull/312#issuecomment-432512790

**Comment by samtstern** [comment] 2018-10-24 17:55
@garytryan I wonder the same thing.  Since that PR is merged now want to try using a local build and see if you get the behavior you expect?

**Comment by garytryan** [comment] 2018-10-24 18:04
@samtstern I just did a local build using that PR and confirmed that this is still an issue

**Comment by samtstern** [comment] 2018-10-24 18:08
Good to know.  Is this a regression since we updated Monaco or is this something that never worked in Firepad?

**Comment by derektlo** [comment] 2018-10-24 18:09
@samtstern this does work with Codemirror, so I believe it is a regression?

**Comment by mikelehen** [comment] 2018-10-24 19:03
This definitely sounds related to #312 (and my guess is it never worked... the monaco integration is still quite new, whereas the codemirror integration is more mature).  So if #312 didn't fix it, then perhaps it's a subtly different issue or the fix for #312 wasn't quite complete. :/  @oliverlin, any interest in taking a look?

FWIW- I tried to repro with examples/monaco.html, but neither cmd+/ or cmd-click had any effect. I guess those features aren't enabled in the example?

**Comment by derektlo** [comment] 2018-10-24 19:11
Reverted to this commit:
`9e70ccd (HEAD -> master) Changed monaco-adapter to respect line endings when calculating positions (#303)`

Still an issue

**Comment by oliverlin** [comment] 2018-10-25 02:04
I tried both scenarios and they are both fixed by #312. To enable the comment feature in monaco, you need to specify the language. Just opened a PR to include this https://github.com/FirebaseExtended/firepad/pull/314

**Closed** 2019-02-28 19:36 UTC
