### ISSUE TITLE
V1.5.0 Monaco Support Broken

### ISSUE THREAD

**Issue by dangys** [FirebaseExtended/firepad#305] opened 2018-08-16 20:33 UTC
https://kodmi.com/explorer/kodi/tsts/examples/monaco.html

As shown in my fresh installed version of v1.5.0 when ever you add too many lines, or a too many blank returns or start to add code tags it breaks and throws javascript errors in the debug console. 

Then if you where to look as the live version from another browser it stops rendering collab text and anything past the first line.

It also does not support "quick type function feature" as per the original Monaco does.

**Comment by mikelehen** [comment] 2018-08-16 20:49
cc/ @pranjaltale16 who implemented the Monaco support.

**Comment by dangys** [comment] 2018-08-17 00:44
I did the fresh install myself.. cloned git, npm install, then used grunt to finish install. Then I just browsed to the example/Monaco.html

**Comment by dididy** [comment] 2018-08-24 21:46
Same problem either.

**Comment by brijeshb42** [comment] 2018-09-03 13:51
Setting first this and then passing it to firepad - 

```js
editor.onDidBlurEditor = editor.onDidBlurEditorWidget;
editor.onDidFocusEditor = editor.onDidFocusEditorWidget;

// editor is instance of monaco editor
```

will fix your error, assuming you are using the latest version of monaco and firepad is using `0.13.1`.

**Comment by ddunkin** [comment] 2018-10-22 18:12
Fixed by #311.

**Comment by garytryan** [comment] 2018-10-22 22:14
This still seems to be an issue.

To reproduce:
1. press Tab
2. Enter
3. Press any character key

Result:
You should see this error message:

```
editor.main.js:129 Uncaught Error: sendOperation() called with invalid operation.

Error: sendOperation() called with invalid operation.
    at assert (firepad.js:1693)
```

which is this line:
```
assert(this.document_.targetLength === operation.baseLength, "sendOperation() called with invalid operation.");
```

**Comment by ddunkin** [comment] 2018-10-23 05:31
The other (original?) problem appears to be that Monaco sends multiple changes, e.g. removing whitespace from a line, but only the first change is processed.
https://github.com/FirebaseExtended/firepad/blob/9785ebd35e1bce58ee44dfadf334a35f42aa8f86/lib/monaco-adapter.js#L58-L87

**Comment by garytryan** [comment] 2018-10-23 16:23
@ddunkin this seems to be fixed by https://github.com/FirebaseExtended/firepad/pull/312

**Comment by ddunkin** [comment] 2018-10-23 16:36
Nice, that’s much cleaner than the way I was trying to fix it with composite operations.

**Comment by luminaxster** [comment] 2018-12-11 22:45
pushing this fix to current npm?

**Comment by mikelehen** [comment] 2018-12-14 21:45
I've just pushed v1.5.1 to npm.  Sorry for the delay!

**Closed by mikelehen** 2018-12-14 21:45 UTC
